export const FILTER_LAUNCH_YEAR = 'FILTER_LAUNCH_YEAR';

export const FILTER_LAUNCH_SUCCESSFUL = 'FILTER_LAUNCH_SUCCESSFUL';

export const FILTER_LANDING_SUCCESSFUL = 'FILTER_LANDING_SUCCESSFUL';

export const CLEAR_FILTER = 'CLEAR_FILTER';
